DROP TABLE IF EXISTS `pessoas`;
CREATE TABLE IF NOT EXISTS `pessoas` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(150) COLLATE UTF8_BIN NOT NULL,
    `nomeMae` VARCHAR(150) COLLATE UTF8_BIN,
    `nomePai` VARCHAR(150) COLLATE UTF8_BIN,
    `estatoCivil` VARCHAR(25) COLLATE UTF8_BIN,
    `naturalidade` VARCHAR(50) COLLATE UTF8_BIN,
    `numRG` BIGINT(15),
    `numCPF` BIGINT(11) NOT NULL,
    `numTituloEleitor` BIGINT(15),
    PRIMARY KEY (`id`)
)  ENGINE=MYISAM AUTO_INCREMENT=15 DEFAULT CHARSET=UTF8 COLLATE = UTF8_BIN;